### PR TITLE
added a new java file-standard multi select automation test

### PR DESCRIPTION
**Pull request by tylee17**
added a new java file automating a demo website
standard multi select

### CODE REVIEW

**Review by ajf876 — APPROVED** [review]
Looks good.

**Comment by EvaGao88** [comment]
:)

**Review by EvaGao88 — COMMENTED** [review]
👍🏻

**Comment by chloeonrails** [comment]
I like the loop 👍

**Review by chloeonrails — APPROVED** [review]
I learned something new from your code!

**Comment by tylee17** [comment]
> 👍🏻

can you approve it? so i can merge it. thanks  ;)

**Review by qingyuanre1 — APPROVED** [review]
Nice code! Learned something new, thx ^^

**Pull request merged**
